const colors = require("tailwindcss/colors");
const defaultTheme = require("tailwindcss/defaultTheme");
const rootColors = require("./colors");
const aemStyles = require("./plugins/aem-styles");

module.exports = {
  mode: "jit",
  darkMode: "class",
  corePlugins: {
    container: false,
  },
  theme: {
    extend: {
      gridTemplateColumns: {
        "25-75": "1fr 3fr",
        "75-25": "3fr 1fr",
        "33-66": "1fr 2fr",
        "66-33": "2fr 1fr",
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: "100ch",
          }
        }
      },
      backgroundColor: {
        "text": "var(--color-text)",
        "text-hover": "var(--color-text-hover)",
        "text-muted": "var(--color-text-muted)",
        "text-accent": "var(--color-text-accent)",
        "text-accent-hover": "var(--color-text-accent-hover)",
        "fill": "var(--color-fill)",
        "fill-hover": "var(--color-fill-hover)",
        "fill-muted": "var(--color-muted)",
        "fill-accent": "var(--color-fill-accent)",
        "fill-accent-hover": "var(--color-fill-accent-hover)",
        "white": "rgb(255,255,255)",
        "light-gray": "rgba(0,0,0,.125)",
        "black": "rgb(0,0,0)",
      },
      boxShadow: {
        "floating": "0 0px 50px -5px rgba(0,0,0,0.1),0 10px 10px -5px rgba(0,0,0,0.04)",
      },
      textColor: {
        DEFAULT: "var(--color-text)",
        "text": "var(--color-text)",
        "text-hover": "var(--color-text-hover)",
        "text-muted": "var(--color-text-muted)",
        "text-accent": "var(--color-text-accent)",
        "text-accent-hover": "var(--color-text-accent-hover)",
        "fill": "var(--color-fill)",
        "fill-hover": "var(--color-fill-hover)",
        "fill-muted": "var(--color-muted)",
        "fill-accent": "var(--color-fill-accent)",
        "fill-accent-hover": "var(--color-fill-accent-hover)",
        "white": "rgb(255,255,255)",
        "black": "rgb(0,0,0)",
        "transparent": "transparent",
      },
      divideColor: {
        DEFAULT: "var(--color-text)",
        "text": "var(--color-text)",
        "text-hover": "var(--color-text-hover)",
        "text-muted": "var(--color-text-muted)",
        "text-accent": "var(--color-text-accent)",
        "text-accent-hover": "var(--color-text-accent-hover)",
        "fill": "var(--color-fill)",
        "fill-hover": "var(--color-fill-hover)",
        "fill-muted": "var(--color-muted)",
        "fill-accent": "var(--color-fill-accent)",
        "fill-accent-hover": "var(--color-fill-accent-hover)",
        "white": "rgb(255,255,255)",
        "black": "rgb(0,0,0)",
      },
      borderColor: {
        DEFAULT: "var(--color-text)",
        "text": "var(--color-text)",
        "text-hover": "var(--color-text-hover)",
        "text-muted": "var(--color-text-muted)",
        "text-accent": "var(--color-text-accent)",
        "text-accent-hover": "var(--color-text-accent-hover)",
        "fill": "var(--color-fill)",
        "fill-hover": "var(--color-fill-hover)",
        "fill-muted": "var(--color-muted)",
        "fill-accent": "var(--color-fill-accent)",
        "fill-accent-hover": "var(--color-fill-accent-hover)",
        "white": "rgb(255,255,255)",
        "black": "rgb(0,0,0)",
      },
      ringColor: {
        DEFAULT: "var(--color-fill-accent)",
      },
      transitionDelay: {
        400: "400ms",
      },
      transitionDuration: {
        400: "400ms",
      },
    },
    colors: {
      "high-contrast-light": {},
      light: {
        ":root": rootColors.light[":root"],
        primary: {
          DEFAULT: "rgb(66, 137, 236)",
          inverted: "rgb(235,235,235)",
          hover: "rgb(62, 119, 200)",
          "inverted-hover": "rgb(255,255,255)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "text-accent": "rgb(235, 235, 235)",
          "text-accent-hover": "rgb(255, 255, 255)",
          "fill": "rgb(66, 137, 236)",
          "fill-hover": "rgb(62, 119, 200)",
          "fill-muted": "rgb(121, 164, 224)",
          "fill-accent": rootColors.secondary.fill,
          "fill-accent-hover": rootColors.secondary["fill-hover"],
        },
        secondary: {
          DEFAULT: "rgb(40,49,67)",
          inverted: "rgb(194,202,219)",
          hover: "rgb(21,26,35)",
          "inverted-hover": "rgb(210,216,228)",

          "text": "rgb(194, 202, 219)",
          "text-hover": "rgb(210, 216, 228)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": "rgb(40, 49, 67)",
          "fill-hover": "rgb(29, 37, 50)",
          "fill-muted": "rgb(121, 164, 224)",
          "fill-accent": rootColors.primary.fill,
          "fill-accent-hover": rootColors.primary["fill-hover"],
        },
        success: {
          DEFAULT: colors.green["500"],
          inverted: "rgb(255,255,255)",
          hover: colors.green["800"],
          "inverted-hover": "rgb(235,235,235)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "text-accent": "rgb(235, 235, 235)",
          "text-accent-hover": "rgb(255, 255, 255)",
          "fill": colors.green["500"],
          "fill-hover": colors.green["600"],
          "fill-muted": colors.green["400"],
          "fill-accent": "rgb(40,49,67)",
          "fill-accent-hover": "rgb(56,60,69)",
        },
        danger: {
          DEFAULT: colors.red["500"],
          inverted: "rgb(255,255,255)",
          hover: colors.red["800"],
          "inverted-hover": "rgb(235,235,235)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "text-accent": "rgb(235, 235, 235)",
          "text-accent-hover": "rgb(255, 255, 255)",
          "fill": colors.red["500"],
          "fill-hover": colors.red["600"],
          "fill-muted": colors.red["400"],
          "fill-accent": "rgb(40,49,67)",
          "fill-accent-hover": "rgb(56,60,69)",
        },
        warning: {
          DEFAULT: colors.yellow["200"],
          inverted: "rgb(30,30,30)",
          hover: colors.yellow["400"],
          "inverted-hover": "rgb(10,10,10)",

          "text": "rgb(40,49,67)",
          "text-hover": "rgb(21,26,35)",
          "text-muted": "rgb(121, 164, 224)",
          "text-accent": "rgb(40,49,67)",
          "text-accent-hover": "rgb(21,26,35)",
          "fill": colors.yellow["200"],
          "fill-hover": colors.yellow["400"],
          "fill-muted": colors.yellow["100"],
          "fill-accent": "rgb(40,49,67)",
          "fill-accent-hover": "rgb(56,60,69)",
        },
        info: {
          DEFAULT: colors.purple["400"],
          inverted: "rgb(255,255,255)",
          hover: colors.purple["800"],
          "inverted-hover": "rgb(235,235,235)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "text-accent": "rgb(235, 235, 235)",
          "text-accent-hover": "rgb(255, 255, 255)",
          "fill": colors.purple["500"],
          "fill-hover": colors.purple["600"],
          "fill-muted": colors.purple["400"],
          "fill-accent": "rgb(40,49,67)",
          "fill-accent-hover": "rgb(56,60,69)",
        },
        light: {
          DEFAULT: "rgb(236, 238, 243)",
          inverted: "rgb(40,49,67)",
          hover: "rgb(204, 211, 224)",
          "inverted-hover": "rgb(21,26,35)",

          "text": "rgb(40,49,67)",
          "text-hover": "rgb(21,26,35)",
          "text-muted": "rgb(121, 164, 224)",
          "text-accent": "rgb(40,49,67)",
          "text-accent-hover": "rgb(21,26,35)",
          "fill": "rgb(236, 238, 243)",
          "fill-hover": "rgb(204, 211, 224)",
          "fill-muted": "rgb(236, 238, 243)",
          "fill-accent": "rgb(40,49,67)",
          "fill-accent-hover": "rgb(56,60,69)",
        },
        dark: {
          DEFAULT: "rgb(37, 73, 123)",
          inverted: "rgb(250, 252, 255)",
          hover: "rgb(30, 64, 113)",
          "inverted-hover": "rgb(255, 255, 255)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "text-accent": "rgb(235, 235, 235)",
          "text-accent-hover": "rgb(255, 255, 255)",
          "fill": "rgb(37, 73, 123)",
          "fill-hover": "rgb(30, 64, 113)",
          "fill-muted": "rgb(30, 64, 113)",
          "fill-accent": "rgb(40,49,67)",
          "fill-accent-hover": "rgb(56,60,69)",
        },
        link: {
          DEFAULT: colors.blue["600"],
          inverted: "rgb(255,255,255)",
          hover: colors.blue["800"],
          "inverted-hover": "rgb(235,235,235)",

          "text": "rgb(40,49,67)",
          "text-hover": "rgb(56,60,69)",
          "text-muted": "rgb(121, 164, 224)",
          "text-accent": "rgb(235, 235, 235)",
          "text-accent-hover": "rgb(255, 255, 255)",
          "fill": "rgb(37, 73, 123)",
          "fill-hover": "rgb(30, 64, 113)",
          "fill-muted": "rgb(30, 64, 113)",
          "fill-accent": "rgb(40,49,67)",
          "fill-accent-hover": "rgb(56,60,69)",
        },
        white: {
          DEFAULT: "white",
          inverted: "rgb(21,26,35)",
          hover: "rgb(255,255,255)",
          "inverted-hover": "rgb(2,2,3)",
          ...rootColors.light[":root"]
        },
        black: {
          DEFAULT: "rgb(30,30,30)",
          inverted: "rgb(255,255,255)",
          hover: "rgb(10,10,10)",
          "inverted-hover": "rgb(235,235,235)",
          ...rootColors.dark[":root"]
        },
        transparent: {
          DEFAULT: "transparent",
          inverted: "transparent",
          hover: "transparent",
          "inverted-hover": "transparent",
          "fill": "transparent",
        },
        gray: {
          DEFAULT: colors.gray["400"],
          ...colors.gray,
        }
      },
      "high-contrast-dark": {},
      dark: {
        ":root": rootColors.dark[":root"],
        primary: {
          DEFAULT: "rgb(66, 137, 236)",
          inverted: "rgb(235,235,235)",
          hover: "rgb(62, 119, 200)",
          "inverted-hover": "rgb(255,255,255)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": "rgb(66, 137, 236)",
          "fill-hover": "rgb(62, 119, 200)",
          "fill-muted": "rgb(121, 164, 224)",
          "accent": "rgb(40,49,67)",
          "accent-hover": "rgb(56,60,69)",
        },
        secondary: {
          DEFAULT: "rgb(40,49,67)",
          inverted: "rgb(194,202,219)",
          hover: "rgb(21,26,35)",
          "inverted-hover": "rgb(210,216,228)",

          "text": "rgb(194, 202, 219)",
          "text-hover": "rgb(210, 216, 228)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": "rgb(40, 49, 67)",
          "fill-hover": "rgb(29, 37, 50)",
          "fill-muted": "rgb(121, 164, 224)",
          "accent": "rgb(66, 137, 236)",
          "accent-hover": "rgb(62, 119, 200)",
        },

        success: {
          DEFAULT: colors.green["500"],
          inverted: "rgb(255,255,255)",
          hover: colors.green["800"],
          "inverted-hover": "rgb(235,235,235)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": colors.green["500"],
          "fill-hover": colors.green["600"],
          "fill-muted": colors.green["400"],
          "accent": "rgb(40,49,67)",
          "accent-hover": "rgb(56,60,69)",
        },
        danger: {
          DEFAULT: colors.red["500"],
          inverted: "rgb(255,255,255)",
          hover: colors.red["800"],
          "inverted-hover": "rgb(235,235,235)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": colors.red["500"],
          "fill-hover": colors.red["600"],
          "fill-muted": colors.red["400"],
          "accent": "rgb(40,49,67)",
          "accent-hover": "rgb(56,60,69)",
        },
        warning: {
          DEFAULT: colors.yellow["200"],
          inverted: "rgb(30,30,30)",
          hover: colors.yellow["400"],
          "inverted-hover": "rgb(10,10,10)",

          "text": "rgb(40,49,67)",
          "text-hover": "rgb(21,26,35)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": colors.yellow["200"],
          "fill-hover": colors.yellow["400"],
          "fill-muted": colors.yellow["100"],
          "accent": "rgb(40,49,67)",
          "accent-hover": "rgb(56,60,69)",
        },
        info: {
          DEFAULT: colors.purple["400"],
          inverted: "rgb(255,255,255)",
          hover: colors.purple["800"],
          "inverted-hover": "rgb(235,235,235)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": colors.purple["500"],
          "fill-hover": colors.purple["600"],
          "fill-muted": colors.purple["400"],
          "accent": "rgb(40,49,67)",
          "accent-hover": "rgb(56,60,69)",
        },
        light: {
          DEFAULT: "rgb(236, 238, 243)",
          inverted: "rgb(40,49,67)",
          hover: "rgb(204, 211, 224)",
          "inverted-hover": "rgb(21,26,35)",

          "text": "rgb(194, 202, 219)",
          "text-hover": "rgb(210, 216, 228)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": "rgb(18, 28, 48)",
          "fill-hover": "rgb(27, 38, 60)",
          "fill-muted": "rgb(19, 28, 45)",
          "accent": "rgb(66, 137, 236)",
          "accent-hover": "rgb(62, 119, 200)",
        },
        dark: {
          DEFAULT: "rgb(37, 73, 123)",
          inverted: "rgb(250, 252, 255)",
          hover: "rgb(30, 64, 113)",
          "inverted-hover": "rgb(255, 255, 255)",

          "text": "rgb(235, 235, 235)",
          "text-hover": "rgb(255, 255, 255)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": "rgb(37, 73, 123)",
          "fill-hover": "rgb(30, 64, 113)",
          "fill-muted": "rgb(30, 64, 113)",
          "accent": "rgb(40,49,67)",
          "accent-hover": "rgb(56,60,69)",
        },
        link: {
          DEFAULT: colors.blue["600"],
          inverted: "rgb(255,255,255)",
          hover: colors.blue["800"],
          "inverted-hover": "rgb(235,235,235)",

          "text": "rgb(40,49,67)",
          "text-hover": "rgb(56,60,69)",
          "text-muted": "rgb(121, 164, 224)",
          "fill": "rgb(37, 73, 123)",
          "fill-hover": "rgb(30, 64, 113)",
          "fill-muted": "rgb(30, 64, 113)",
          "accent": "rgb(40,49,67)",
          "accent-hover": "rgb(56,60,69)",
        },
        white: {
          DEFAULT: "white",
          inverted: "rgb(21,26,35)",
          hover: "rgb(255,255,255)",
          "inverted-hover": "rgb(2,2,3)",
          ...rootColors.light[":root"]
        },
        black: {
          DEFAULT: "rgb(30,30,30)",
          inverted: "rgb(255,255,255)",
          hover: "rgb(10,10,10)",
          "inverted-hover": "rgb(235,235,235)",
          ...rootColors.dark[":root"]
        },
        transparent: {
          DEFAULT: "transparent",
          inverted: "transparent",
          hover: "transparent",
          "inverted-hover": "transparent",
        },
        gray: {
          DEFAULT: colors.gray["400"],
          ...colors.gray,
        }
      },
      transparent: {
        DEFAULT: "transparent",
        inverted: "transparent",
        hover: "transparent",
        "inverted-hover": "transparent",
      },

    },
    fontFamily: {
      "sans": ["system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "Noto Sans", "Liberation Sans", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"]
    },
    screens: {
      "sm": { "max": "767px" },
      "md": "768px",
      "lg": "1024px",
      "xl": "1280px",
    },
    icons: [
      "list",
      "x",
      "arrow-up",
      "arrow-right",
      "arrow-down",
      "arrow-left",
      "caret-up-fill",
      "caret-right-fill",
      "caret-down-fill",
      "caret-left-fill",
      "chevron-up",
      "chevron-right",
      "chevron-down",
      "chevron-left",
      "geo-alt",
      "geo-alt-fill",
      "globe",
      "plus",
      "dash",
      "search",
      "facebook",
      "twitter",
      "instagram",
      "youtube",
      "google",
      "linkedin",
      "github",
      "messenger",
      "reddit",
      "skype",
      "slack",
      "telegram",
      "twitch",
      "whatsapp",
      "discord",
    ],
    spacing: () => {
      const styles = {};
      [0, "0.5", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 20, 24, "px"].forEach(space => styles[space] = defaultTheme.spacing[space.toString()]);
      return styles;
    },
  },
  variants: {
    extend: {
      alignItems: ["var"],
      backgroundColor: ["var", "hover-var"],
      backgroundBlendMode: ["var"],
      backdropBlur: ["var"],
      borderRadius: ["var"],
      boxShadow: ["var"],
      flexDirection: ["var"],
      flexGrow: ["var"],
      flexWrap: ["var"],
      fontSize: ["var"],
      gap: ["var", "parent-var"],
      gridTemplateColumns: ["var"],
      inset: ["active", "hover", "focus"],
      justifyContent: ["var"],
      maxWidth: ["var"],
      margin: ["var"],
      padding: ["var"],
      // space: ["var"],
      textAlign: ["var"],
      textColor: ["var", "hover-var"],
      width: ["aem-GridColumn"],
      ringColor: ["active"]
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("./plugins/icons"),
    require("./plugins/css-vars-variants"),
    require("./plugins/aem-grid"),
    require("./plugins/color-css-vars"),
    aemStyles("./src/styles/index.js"),
  ],
  purge: {
    enabled: true,
    content: [
      "./src/template/policies.json",
      "./src/components/**/**/*.js",
      "./src/components/**/**/*.css",
      "./src/site/js/*.js",
      "./src/site/css/*.css",
      "./tailwind.config.js",
    ],
    css: ["./src/main.css"],
    options: {
      safelist: [/^aem-GridColumn--/],
    }
  },
};
