module.exports = {
  'core/wcm/components/accordion/v1/accordion': require('../components/accordion/styles/index.js'),
  'core/wcm/components/breadcrumb/v2/breadcrumb': require('../components/breadcrumb/styles/index.js'),
  'core/wcm/components/button/v1/button': require('../components/button/styles/index.js'),
  'core/wcm/components/carousel/v1/carousel': require('../components/carousel/styles/index.js'),
  'core/wcm/components/container/v1/container': require('../components/container/styles/index.js'),
  'core/wcm/components/contentfragment/v1/contentfragment': require('../components/contentfragment/styles/index.js'),
  'core/wcm/components/contentfragmentlist/v1/contentfragmentlist': require('../components/contentfragmentlist/styles/index.js'),
  'core/wcm/components/download/v1/download': require('../components/download/styles/index.js'),
  'core/wcm/components/embed/v1/embed': require('../components/embed/styles/index.js'),
  'core/wcm/components/experiencefragment/v1/experiencefragment': require('../components/experiencefragment/styles/index.js'),
  'core/wcm/components/form/container/v2/container': require('../components/form/styles/index.js'),
  'core/wcm/components/form/button/v2/button': require('../components/form-button/styles/index.js'),
  'core/wcm/components/form/options/v2/options': require('../components/form-options/styles/index.js'),
  'core/wcm/components/form/text/v2/text': require('../components/form-text/styles/index.js'),
  'core/wcm/components/image/v2/image': require('../components/image/styles/index.js'),
  'core/wcm/components/languagenavigation/v1/languagenavigation': require('../components/languagenavigation/styles/index.js'),
  'core/wcm/components/list/v2/list': require('../components/list/styles/index.js'),
  'core/wcm/components/navigation/v1/navigation': require('../components/navigation/styles/index.js'),
  'core/wcm/components/pdfviewer/v1/pdfviewer': require('../components/pdfviewer/styles/index.js'),
  'core/wcm/components/progressbar/v1/progressbar': require('../components/progressbar/styles/index.js'),
  'core/wcm/components/search/v1/search': require('../components/search/styles/index.js'),
  'core/wcm/components/separator/v1/separator': require('../components/separator/styles/index.js'),
  'core/wcm/components/tabs/v1/tabs': require('../components/tabs/styles/index.js'),
  'core/wcm/components/teaser/v1/teaser': require('../components/teaser/styles/index.js'),
  'core/wcm/components/text/v2/text': require('../components/text/styles/index.js'),
  'core/wcm/components/title/v2/title': require('../components/title/styles/index.js'),
}