const { CQStyleGroups } = require("../../../../aem-blueprint/styles/index")

module.exports = new CQStyleGroups([
  require("./presets"),
  require("../../_common/styles/background-color"),
  require("../../_common/styles/animation-fade"),
  require("../../_common/styles/animation-zoom"),
  require("../../_common/styles/animation-duration"),
  require("../../_common/styles/animation-delay"),
  require("../../_common/styles/flex-grow"),
  require("../../_common/styles/max-width"),
  require("../../_common/styles/align-items"),
  require("../../_common/styles/justify"),
  require("../../_common/styles/padding"),
  require("./border"),
  require("./rounded"),
  require("./image-size"),
  require("./image-object-fit"),
  require("./image-position"),
  require("./content-gap"),
  require("./content-padding"),
  require("./space-between-image-content"),
  require("./pretitle-styles"),
  require("./text-align"),
  require("./title-size"),
  require("./action-styles"),
  require("./actions-justify"),
  require("../../_common/styles/box-shadow"),
])